config/routes.rb
Rails.application.routes.draw do
  root 'contractors#index'
  post 'contractors/login' => 'contractors#login', as: :contractor_login
  post 'contractors/update_voter_info/:vgi_id' => 'contractors#update_voter_info', as: :update_voter_info
  
  get 'admin' => 'admin#index'
  get 'admin/contractors/:contractor_id' => 'admin#view_contractor', as: :view_contractor
  get 'admin/voters/:voter_id' => 'admin#view_voter', as: :view_voter
  post 'admin/login' => 'admin#login', as: :admin_login
  post 'admin/create_contractor' => 'admin#create_contractor', as: :create_contractor

end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/contractor.rb
class Contractor < ActiveRecord::Base
  validates :email, uniqueness: true
  
  has_many :voter_gathered_infos
  has_many :voters, through: :voter_gathered_infos
end

app/models/voter.rb
class Voter < ActiveRecord::Base
  has_many :voter_gathered_infos
  has_many :contractors, through: :voter_gathered_infos
  
  def full_name
    self.szNameFirst + " " + self.szNameLast
  end
  
  def address
    self.szSitusAddress + ", " + self.szSitusCity + ", " + self.sSitusState + " " + self.sSitusZip
  end
end

app/models/voter_gathered_info.rb
class VoterGatheredInfo < ActiveRecord::Base
  belongs_to :contractor
  belongs_to :voter
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :check_admin, except: [:index, :login]

  def index
    if session[:admin_id]
      @admin = Admin.where(id: session[:admin_id]).first
      @contractors = Contractor.all
    else
      render :login
    end
  end

  def login
    admin = Admin.where(email: params[:email], password: params[:password])

    if admin.empty?
      flash[:error] = "Invalid login"
      render :login
    else
      session[:admin_id] = admin.first.id
      redirect_to action: :index
    end
  end

  def view_contractor
    @contractor = Contractor.where(id: params[:contractor_id])

    if @contractor.empty?
      flash[:error] = "Could not find contractor with ID #{params[:contractor_id]}"
    else
      @contractor = @contractor.first
      @all_voter_infos = @contractor.voter_gathered_infos.order(:voter_id)
      @completed_voter_infos = @all_voter_infos.where.not(email: nil)
    end
  end

  def create_contractor
    contractor = Contractor.new
    contractor.full_name = params[:full_name]
    contractor.email = params[:email]
    # http://stackoverflow.com/a/3572953/1516425
    # TODO(saurabh): password should really be hashed
    # TODO(saurabh): move password generating logic to Contractor model
    contractor.password = rand(36**10).to_s(36)

    if contractor.save
      # TODO(saurabh): move logic for generating random voters to VoterGatheredInfo model?
      # TODO(saurabh): don't include voters that we already have an email for in the original CSV file
      num_voters = params[:num_voters].to_i
      voter_ids = Voter.pluck(:id).shuffle[0..(num_voters-1)]

      for voter_id in voter_ids
        vgi = VoterGatheredInfo.new
        vgi.voter_id = voter_id
        vgi.contractor_id = contractor.id
        vgi.save
      end

      redirect_to action: :index
    else
      flash[:create_contractor_error] = "Contractor with email #{params[:email]} already exists"
      render :index
    end
  end

  def view_voter
    @voter = Voter.where(id: params[:voter_id]).first
    vgis = @voter.voter_gathered_infos
    @email_to_contractors = {}
    @waiting_on_contractors = []
    for vgi in vgis
      unless vgi.email
        @waiting_on_contractors.push(vgi.contractor)
        next
      end

      unless @email_to_contractors.has_key?(vgi.email)
        @email_to_contractors[vgi.email] = []
      end

      @email_to_contractors[vgi.email].push(vgi.contractor)
    end
  end

  private

    def check_admin
      if session[:admin_id]
        @admin = Admin.where(id: session[:admin_id]).first
      else
        # TODO(saurabh): i don't think this works
        render status: :unauthorized
        return false
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController
  def index
    if session[:contractor_id]
      @contractor = Contractor.where(id: session[:contractor_id])
      
      if @contractor.empty?
        # invalid/non-existent contractor_id
        session[:contractor_id] = nil
        render :login
      else
        @contractor = @contractor.first
      end
    else
      render :login
    end
  end

  def login
    contractor = Contractor.where(email: params[:email], password: params[:password])

    if contractor.empty?
      flash[:error] = "Invalid login"
      render :login
    else
      session[:contractor_id] = contractor.first.id
      redirect_to action: :index
    end
  end
  
  def update_voter_info
    contractor = Contractor.where(id: session[:contractor_id]).first
    vgi = contractor.voter_gathered_infos.where(id: params[:vgi_id])
    
    if vgi.empty?
      render json: { error: "Invalid vgi_id" }
    else
      vgi = vgi.first
      vgi.email = params[:email]
      vgi.save
      render nothing: true, status: :ok
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/views/admin/index.html.erb
<h2>All Contractors</h2>

<% for contractor in @contractors %>
  <p>
    <%= link_to "#{contractor.full_name}: #{contractor.email} - #{contractor.password}", view_contractor_path(contractor.id) %>
  </p>
<% end %>

<h2>Create New Contractor</h2>

<span style="color: red;"><%= flash[:create_contractor_error] %></span>

<%= form_tag(create_contractor_path, method: 'post') do %>
  <p>
    <%= label_tag(:full_name, "Full Name") %>
    <%= text_field_tag(:full_name) %>
  </p>

  <p>
    <%= label_tag(:email, "Email") %>
    <%= text_field_tag(:email) %>
  </p>
  
  <p>
    <%= label_tag(:num_voters, "Number of Voters") %>
    <%= text_field_tag(:num_voters) %>
  </p>

  <p>
    <%= submit_tag("Submit") %>
  </p>
<% end %>

<em>Logged in as <%= @admin.full_name %> (<%= @admin.email %>)</em>

app/views/admin/login.html.erb
<h1>Login</h1>

<h2><%= flash[:error] %></h2>

<%= form_tag(admin_login_path, method: 'post') do %>
  <p>
    <%= label_tag(:email, "Email") %>
    <%= text_field_tag(:email) %>
  </p>

  <p>
    <%= label_tag(:password, "Password") %>
    <%= password_field_tag(:password) %>
  </p>

  <p>
    <%= submit_tag("Submit") %>
  </p>
<% end %>

app/views/admin/view_contractor.html.erb
<h2><%= @contractor.full_name %> (<%= @contractor.email %>)</h2>

Completed <b><%= @completed_voter_infos.count %></b> out of <b><%= @all_voter_infos.count %></b>

<% for vgi in @all_voter_infos %>
  <p>
    <%= link_to vgi.voter.full_name, view_voter_path(vgi.voter.id) %> - <%= vgi.voter.address %> - <%= vgi.email || "Email not entered yet" %>
  </p>
<% end %>

app/views/admin/view_voter.html.erb
<h1><%= @voter.full_name %></h1>

<h3><%= @voter.address %></h3>

<% if @email_to_contractors.keys.length > 0 %>
  <h4>Emails:</h4>

  <% if @email_to_contractors.length > 1 %>
    <h4><span style="color: red;">More than 1 unique email</span></h4>
  <% end %>

  <% for email in @email_to_contractors.keys %>
    <p>
      <%# TODO(saurabh): this is a mess %>
      <%= email %> (Added by 
      <% for c in @email_to_contractors[email] %>
        <%= link_to c.full_name, view_contractor_path(c.id) %>,
      <% end %>)
    </p>
  <% end %>
<% end %>

<% if @waiting_on_contractors.length > 0 %>
  <h4>Waiting on contractors to enter email:</h4>

  <% for contractor in @waiting_on_contractors %>
    <p><%= link_to contractor.full_name, view_contractor_path(contractor.id) %></p>
  <% end %>
<% end %>

app/views/contractors/index.html.erb
<h2><%= @contractor.full_name %> (<%= @contractor.email %>)</h2>

<h4>Please fill in information for the following voters</h4>

<% for vgi in @contractor.voter_gathered_infos.order(:voter_id) %>
  <%= form_tag(update_voter_info_path(vgi_id: vgi.id), method: 'post', remote: true) do %>
    <p>
      <%= vgi.voter.full_name %> - <%= vgi.voter.address %>
      &nbsp; &nbsp;<%= text_field_tag :email, vgi.email, { class: :email, vgi_id: vgi.id } %>
      &nbsp;<%= submit_tag "Save" %>
    </p>
  <% end %>
<% end %>

app/views/contractors/login.html.erb
<h1>Login</h1>

<h2><%= flash[:error] %></h2>

<%= form_tag(contractor_login_path, method: 'post') do %>
  <p>
    <%= label_tag(:email, "Email") %>
    <%= text_field_tag(:email) %>
  </p>

  <p>
    <%= label_tag(:password, "Password") %>
    <%= password_field_tag(:password) %>
  </p>

  <p>
    <%= submit_tag("Submit") %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tesla</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>